### ISSUE TITLE
Loading hides the tabs section

### ISSUE THREAD

**Issue by furkanmutlu** [MutluMinds/fullstack-image-app#75]
When new images loading loading spinner is removing tabs from the DOM. 
Tabs should be visible to the user when loading images.

![image](https://user-images.githubusercontent.com/45897337/213793025-afb6b8e3-9183-4671-abfd-d916efe50931.png)

**Comment by ashwanijha1996** [comment]
Hi i am a beginner and i want to contribute to your project.I have 9 months of relevant experience. Can i start my open source contributions from your project?

**Comment by ashwanijha1996** [comment]
Hi i have fixed this bug but i have a question that in which place in the gallery page you want to display loading image?
![Screenshot 2023-12-16 135637](https://github.com/MutluMinds/fullstack-image-app/assets/97039392/fa7e3d28-61d1-45e1-b3fd-0bf0a31b309e)

**Comment by furkanmutlu** [comment]
Hi @ashwanijha1996 thank you for your contribution. You are very welcome to work on any issue you prefer
